### ISSUE TITLE
Point to PROD by default

### ISSUE THREAD

**Issue by rrees** [guardian/facia-tool-node-api#1]
The code forces the environment to be CODE but this makes it hard to reconcile live containers against the API.

**Comment by piuccio** [comment]
I thought [this line](https://github.com/guardian/facia-tool-node-api/blob/master/lib/config.js#L3) was doing the job. I'll check tomorrow, thanks

**Comment by rrees** [comment]
I might be reading it wrong but I think [this line](https://github.com/guardian/facia-tool-node-api/blob/master/controllers/config.js#L17) overrides it explicitly.

This is the container that is not resolving for me:
http://facia-tool.herokuapp.com/config/collection/us-alpha/contributors/feature-stories

**Comment by piuccio** [comment]
LOL I wonder why did I do that :smile:
